# Generated by Django 3.2.7 on 2021-09-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=50)),
                ('repos', models.TextField()),
                ('repo_count', models.IntegerField()),
            ],
        ),
    ]
